# Generated by Django 3.0.2 on 2020-02-24 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('student_year', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('picture', models.URLField()),
                ('bio', models.CharField(max_length=200)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.StudentRatings')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
