# Generated by Django 3.0.3 on 2020-04-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_tutorrequest_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
