# Generated by Django 3.0.2 on 2020-04-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20200408_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='last_name',
        ),
    ]
