# Generated by Django 3.0.3 on 2020-04-15 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_auto_20200414_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestTutor', to='study.Student'),
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
